[project]
name = "diamond-dogs"
version = "0.1.0"
description = "Aplicación para crear, visualizar y guardar modelos de regresión lineal."
readme = "README.md"
authors = [
    { name = "Laura Martin Salvador", email = "laura.msalvador@udc.es" }
]
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
]

[project.scripts]
diamond-dogs = "diamond_dogs:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
